name: Terraform CI

on:
  pull_request:
    branches:
      - main
      - develop

env:
  TF_VERSION: '1.5.0'
  
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Terraform Format Check
      run: terraform fmt -check -recursive
    
    - name: Terraform Init
      run: |
        cd environments/dev
        terraform init
    
    - name: Terraform Validate
      run: |
        cd environments/dev
        terraform validate
    
    - name: Terraform Plan
      run: |
        cd environments/dev
        terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -out=tfplan
    
    - name: Upload Plan
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: environments/dev/tfplan
